### ISSUE TITLE
コード整形＆潜在バグのチェック

### ISSUE THREAD

**Issue by gorogoro-space** [gorogoro-space/Gacha#1]
# 概要
- コード整形＆潜在バグのビルド時チェックを組み込む

# 理由
- 機能に影響ない潜在的なバグ防止＆コーディングルールの自動適用の為

# 詳細
- 以下の対応をしてみる
  - コード整形
    - checkstyle
  - 潜在バグ
    - findbugs

# Note
- Check for potential bugs that do not affect functionality.

**Comment by kubotan** [comment]
再検討時に対応のため、一旦クローズ
